// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// check_name_parser
std::string check_name_parser(std::string const& str);
RcppExport SEXP _listselector_check_name_parser(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string const& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(check_name_parser(str));
    return rcpp_result_gen;
END_RCPP
}
// check_expr_parser
std::string check_expr_parser(std::string const& str);
RcppExport SEXP _listselector_check_expr_parser(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string const& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(check_expr_parser(str));
    return rcpp_result_gen;
END_RCPP
}
// check_attribute_parser
Rcpp::List check_attribute_parser(std::string const& str);
RcppExport SEXP _listselector_check_attribute_parser(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string const& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(check_attribute_parser(str));
    return rcpp_result_gen;
END_RCPP
}
// check_simple_selector_parser
Rcpp::List check_simple_selector_parser(std::string const& str);
RcppExport SEXP _listselector_check_simple_selector_parser(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string const& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(check_simple_selector_parser(str));
    return rcpp_result_gen;
END_RCPP
}
// test
bool test(std::string const& str);
RcppExport SEXP _listselector_test(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string const& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(test(str));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_listselector_check_name_parser", (DL_FUNC) &_listselector_check_name_parser, 1},
    {"_listselector_check_expr_parser", (DL_FUNC) &_listselector_check_expr_parser, 1},
    {"_listselector_check_attribute_parser", (DL_FUNC) &_listselector_check_attribute_parser, 1},
    {"_listselector_check_simple_selector_parser", (DL_FUNC) &_listselector_check_simple_selector_parser, 1},
    {"_listselector_test", (DL_FUNC) &_listselector_test, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_listselector(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
